### ISSUE TITLE
安装核心模块及NGUI导出模块提示ArgumentNullException: Value cannot be null. Parameter name: path2

### ISSUE THREAD

**Issue by SugimotoYuuji** [wechat-miniprogram/minigame-adaptor#3]
Unity 版本：2019.3.7f1 Personal
安装扩展模块时，会有如下错误提示：
ArgumentNullException: Value cannot be null.
Parameter name: path2
![image](https://user-images.githubusercontent.com/35778837/87927133-4f818100-cab5-11ea-9ef7-219a377de447.png)

**Comment by yuanzm** [comment]
2019应该是有问题的，这两天我们内部过下，出个2019的版本。

**Comment by ZyleBallet** [comment]
2018  unity 4.2 好像也有问题,倒出来的小游戏工程,解压后跑不起来

**Comment by ZyleBallet** [comment]
2018 unity 4.2 好像也有问题,倒出来的小游戏工程,解压后跑不起来

**Comment by ZyleBallet** [comment]
2019 失败后,降级到2018 4.2
2018 unity 4.2 好像也有问题,倒出来的小游戏工程,解压后跑不起来,报错

**Comment by ZyleBallet** [comment]
![WechatIMG40](https://user-images.githubusercontent.com/68416947/90995113-8a636100-e5ed-11ea-87b6-0dc3ce90629d.png)

**Comment by yuanzm** [comment]
已经支持
