### ISSUE TITLE
 Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by loooog** [wechat-miniprogram/minigame-adaptor#4]
编译完模拟器屏幕上显示  Error: unable to get local issuer certificate
是什么问题呢，请问

**Comment by loooog** [comment]
Mac上出现了此问题，后来换了Windows，没有这个问题。
不过，弱问下，一般导出来的项目都很大，至少几十M，请问是如何发布到真机的呢？配置分包么？

**Comment by yuanzm** [comment]
方便留个联系方式么，我们可以拉群处理

**Comment by loooog** [comment]
> 方便留个联系方式么，我们可以拉群处理

好的.qq或者微信  877182117
